language: ruby
ruby:
  - 2.6.3
cache: bundler
node_js:
  - 12

services:
  - mongodb

before_install:
  - nvm install 12

before_script:
  - bundle install
  - pushd clients/html && nvm use 12 && yarn install && popd

script:
  - bundle exec rspec
  - cd clients/html && nvm use 12 && yarn test --browsers ChromeHeadless --watch false

after_failure:
  - cd $TRAVIS_BUILD_DIR && ./travis/post_build_results

after_success:
  - cd $TRAVIS_BUILD_DIR && ./travis/post_build_results